# Generated by Django 3.0.3 on 2020-06-27 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('impact', models.IntegerField(default=0)),
                ('likelihood', models.IntegerField(default=0)),
                ('criticality', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_module.RiskCategory')),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('P', 'PDF File'), ('D', 'Document File Doc'), ('x', 'Excel File XLS')], max_length=1)),
                ('file', models.FileField(blank=True, upload_to='documents_files')),
                ('is_active', models.BooleanField(default=False)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_documents', to='main_module.Risk')),
                ('uploader_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
