# Generated by Django 3.0.3 on 2020-06-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0002_riskcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskcategory',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
