# Generated by Django 3.0.3 on 2020-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0003_riskcategory_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskcategory',
            name='hierarcy',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
