# Generated by Django 3.0.3 on 2020-06-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0007_userprofileinfo_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskResiduals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resulted_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_risk', to='main_module.Risk')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_risk', to='main_module.Risk')),
            ],
        ),
    ]
