# Generated by Django 3.0.3 on 2020-06-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0009_incident_incidentissues_issue_loss_lossincident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentissues',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='incidentissues',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='lossincident',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='lossincident',
            name='loss',
        ),
        migrations.AddField(
            model_name='issue',
            name='hierarcy',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='issue',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='IncidentIssues',
        ),
        migrations.DeleteModel(
            name='Loss',
        ),
        migrations.DeleteModel(
            name='LossIncident',
        ),
    ]
