# Generated by Django 3.0.3 on 2020-06-28 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0011_riskcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main_module.Issue'),
        ),
    ]
